services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mechanico_strapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: gateUser@988
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5192:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mechanico_strapi"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - strapi-network

  strapi:
    image: gheshu00/mechanico-strapi
    ports:
      - "1337:1337"
    volumes:
      - ./public/uploads:/app/public/uploads
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - strapi-network

volumes:
  postgres_data:

networks:
  strapi-network:
    driver: bridge
