services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mechanico_strapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: gateUser@988
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mechanico_strapi"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - strapi-network

  strapi:
    build: .
    volumes:
      - ./public/uploads:/app/public/uploads
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - strapi-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strapi.rule=Host(`obrobibini.com`)" # replace with Coolify domain or custom one
      - "traefik.http.routers.strapi.entrypoints=websecure"
      - "traefik.http.routers.strapi.tls.certresolver=letsencrypt"

volumes:
  postgres_data:

networks:
  strapi-network:
    driver: bridge
